### ISSUE TITLE
everything is deprecated

### ISSUE THREAD

**Issue by JuliPodie** [acro5piano/graphql-rest-proxy#212]
Hi,

can someone bump all the versions, its not working with the current node/tsc versions cause of the commonJS, ESmodule stuff
pls fix <3

Kind Regards
Juli

**Comment by acro5piano** [comment]
@JuliPodie Thanks. I'll work on it.

**Comment by acro5piano** [comment]
I've taken a look at this repository for the first time in 2 years. This project uses lots of old stuff. I should update them in more modern way!

**Comment by acro5piano** [comment]
Hi @JuliPodie, I've updated almost all deps in v0.6.4. If you have still problems with it, feel free to let me know. Thanks!
